config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/monitoring'

  get 'welcome/why'
  get 'welcome/index'
  get 'welcome/server'
  get 'welcome/client'
  get 'welcome/redis'
  get 'welcome/best_practices'
  get 'welcome/warnings'

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def redis
    @redis = Redis.new(:url => 'redis://127.0.0.1:6379/12')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sidekiq, Wat is da shit?!</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Sidekiq, Wat is da shit?!', root_path, class: 'navbar-brand' %></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Redis', welcome_redis_path %></a></li>
            <li><%= link_to 'Monitoring', sidekiq_web_path, target: '_blank' %></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container main">
      <%= yield %>
    </div><!-- /.container -->
  </body>
</html>

app/views/welcome/redis.html.erb
<table class="table">
  <thead>
    <tr><th>> COMMAND Redis: KEYS sidekiq-wat-da-shit*</th></tr>
  </thead>
  <tbody>
    <% @redis.keys('sidekiq-wat-da-shit*').each do |k| %>
    <tr><td><%= k %> : <%= @redis.type(k) %></td></tr>
    <% end %>
  </tbody>
</table>

<table class="table">
  <thead>
    <tr><th>> COMMAND Redis: SMEMBERS sidekiq-wat-da-shit:queues</th></tr>
  </thead>
  <tbody>
    <% @redis.smembers('sidekiq-wat-da-shit:queues').each do |m| %>
    <tr><td><%= m %></td></tr>
    <% end %>
  </tbody>
</table>

<table class="table">
  <thead>
    <tr><th>> COMMAND Redis: LRANGE sidekiq-wat-da-shit:queue:default 0 -1</th></tr>
  </thead>
  <tbody>
    <% @redis.lrange('sidekiq-wat-da-shit:queue:default', 0, -1).each do |r| %>
    <tr><td><%= r %></td></tr>
    <% end %>
  </tbody>
</table>

<table class="table">
  <thead>
    <tr>
      <th>> COMMAND Redis: SMEMBERS sidekiq-wat-da-shit:processes</th>
    </tr>
  </thead>
  <tbody>
    <% @redis.smembers('sidekiq-wat-da-shit:processes').each do |p| %>
    <% key = "sidekiq-wat-da-shit:#{ p }" %>
    <tr>
      <td><%= p %> : <%= @redis.type(key) %></td>
    </tr>
    <tr>
      <td>
        <table class="table">
          <thead>
            <tr>
              <th>> COMMAND Redis: HGETALL <%= key %></th>
            </tr>
          </thead>
          <tbody>
            <% @redis.hgetall(key).each do |w| %>
            <tr><td><%= w %></td></tr>
            <% end %>
          </tbody>
        </table>
        <table class="table">
          <thead>
            <tr>
              <th>> COMMAND Redis: HGETALL <%= key %>:workers</th>
            </tr>
          </thead>
          <tbody>
            <% @redis.hgetall("#{ key }:workers").each do |w| %>
            <tr><td><%= w %></td></tr>
            <% end %>
          </tbody>
        </table>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<table class="table">
  <thead>
    <tr>
      <th>> COMMAND Redis: GET sidekiq-wat-da-shit:stat:processed</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @redis.get('sidekiq-wat-da-shit:stat:processed') %></td>
    </tr>
  </tbody>
</table>

<table class="table">
  <thead>
    <tr>
      <th>> COMMAND Redis: ZRANGE sidekiq-wat-da-shit:retry 0 -1</th>
    </tr>
  </thead>
  <tbody>
    <% @redis.zrange('sidekiq-wat-da-shit:retry', 0, -1).each do |r| %>
    <tr>
      <td><%= r %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<table class="table">
  <thead>
    <tr>
      <th>> COMMAND Redis: ZRANGE sidekiq-wat-da-shit:dead 0 -1</th>
    </tr>
  </thead>
  <tbody>
    <% @redis.zrange('sidekiq-wat-da-shit:dead', 0, -1).each do |r| %>
    <tr>
      <td><%= r %></td>
    </tr>
    <% end %>
  </tbody>
</table>